-- INSERT INTO contents (content_path, created_at, updated_at) values ('image001.jpg', date('now'), date('now'));
-- INSERT INTO contents (content_path, created_at, updated_at) values ('image002.jpg', date('now'), date('now'));
-- INSERT INTO contents (content_path, created_at, updated_at) values ('image003.jpg', date('now'), date('now'));
-- INSERT INTO contents (content_path, created_at, updated_at) values ('image004.jpg', date('now'), date('now'));
-- INSERT INTO contents (content_path, created_at, updated_at) values ('image005.jpg', date('now'), date('now'));
-- INSERT INTO contents (content_path, created_at, updated_at) values ('image006.jpg', date('now'), date('now'));
-- INSERT INTO contents (content_path, created_at, updated_at) values ('image007.jpg', date('now'), date('now'));
-- INSERT INTO contents (content_path, created_at, updated_at) values ('image008.jpg', date('now'), date('now'));
-- INSERT INTO contents (content_path, created_at, updated_at) values ('image009.jpg', date('now'), date('now'));
-- INSERT INTO contents (content_path, created_at, updated_at) values ('image010.jpg', date('now'), date('now'));


INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (2, 10, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (4, 10, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (2, 5, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (1, 7, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (3, 5, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (6, 9, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (5, 9, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (7, 9, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (3, 4, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (1, 10, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (4, 7, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (6, 10, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (3, 7, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (1, 3, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (5, 6, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (3, 6, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (1, 9, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (5, 8, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (3, 9, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (8, 9, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (4, 8, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (2, 8, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (4, 9, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (2, 7, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (1, 6, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (4, 6, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (2, 3, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (4, 5, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (3, 10, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (6, 8, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (8, 10, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (7, 8, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (1, 4, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (2, 4, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (7, 10, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (1, 5, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (5, 10, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (1, 8, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (2, 9, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (3, 8, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (6, 7, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (5, 7, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (2, 6, 0, date('now'), date('now'));
INSERT INTO pairs (a, b, count, created_at, updated_at) VALUES (1, 2, 0, date('now'), date('now'));

