#!/usr/bin/env python
#
# outputs toplevel ini variables as environment variables
import os
import configparser

if (len(sys.argv) < 2):
    print("Usage: %s $CONFIG" % (sys.argv[0]))
    sys.exit(1)

config = configparser.ConfigParser()
config.read(sys.argv[1])

os.environ['DEBUSSY'] = '1'
