#!/usr/bin/env python
# getMarkerFrames $CSV
#   Test algorithm for reimplementation in fitting application
import csv
import sys
from collections import defaultdict

if (len(sys.argv) < 2):
    print("Usage: %s $CSVPATH" % (sys.argv[0]))
    sys.exit(1)

path = sys.argv[1]
f = open(path, 'r')
cols = defaultdict(int)
reader = csv.reader(f, delimiter=',')

clicks = []
lastClick = 0
matchCount = 0
frame = 0

first = True
for row in reader:
    if first:
        first = False
        continue

    for i in range(len(row)):
        cols[i] += 1

        if i == 0:
            frame = int(row[i].strip())

        if i == 4:
            click = int(row[i].strip())
            if (click > lastClick):
                matchCount += 1

            else:
                if (matchCount > 1):
                    clicks += [frame - lastClick]
                matchCount = 0

                if (click > 0):
                    matchCount += 1

            lastClick = click

if (matchCount > 1):
    clicks += [frame - lastClick]

print("click count:", len(clicks))
print("clicks", clicks)
